#! /usr/bin/env php
<?php

set_time_limit(0);

require_once __DIR__.'/../vendor/autoload.php';

$app = require __DIR__.'/app.php';
require __DIR__.'/config/cli.php';

$cli = $app['console'];
$cli->run();
